FROM golang:1.20.1-bullseye

WORKDIR /app

ARG MONGO_CONNECTION_STRING
ENV MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
# postgres
ARG DB_USERNAME
ENV DB_USERNAME=${DB_USERNAME}
ARG DB_PASSWORD
ENV DB_PASSWORD=${DB_PASSWORD}
ARG DB_NAME
ENV DB_NAME=${DB_NAME}
ARG DB_PORT
ENV DB_PORT=${DB_PORT}
ARG DB_SSLMODE
ENV DB_SSLMODE=${DB_SSLMODE}
ARG DB_HOST
ENV DB_HOST=${DB_HOST}
# africa's talking
ARG AFRICAS_TALKING_API_KEY
ENV AFRICAS_TALKING_API_KEY=${AFRICAS_TALKING_API_KEY}
ARG AFRICAS_TALKING_USERNAME
ENV AFRICAS_TALKING_USERNAME=${AFRICAS_TALKING_USERNAME}
ARG AFRICAS_TALKING_SHORT_CODE
ENV AFRICAS_TALKING_SHORT_CODE=${AFRICAS_TALKING_SHORT_CODE}
# app config
ARG GO_ENV
ENV GO_ENV=${GO_ENV}
# Sentry 
ARG SENTRY_ENV
ENV SENTRY_ENV=${SENTRY_ENV}
ARG SENTRY_DNS
ENV SENTRY_DNS=${SENTRY_DNS}

COPY . ./

RUN go mod download 

RUN go build -o main 

RUN ls -la

CMD ["./main"]