name: Divvly Tracking Service

on:
  push: 
    branches: [main, WAK-Sprint-2023-14, WAK-Sprint-2023-15, WAK-Sprint-2023-16, mobile-tracking] #sprint release branches have been included

  pull_request:
    branches: [main, WAK-Sprint-2023-14, WAK-Sprint-2023-15, WAK-Sprint-2023-16, mobile-tracking] #sprint release branches have been included

jobs: 
  test_handlers:
    if: true
    runs-on: self-hosted
    env:
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      AFRICAS_TALKING_API_KEY: ${{ secrets.AFRICAS_TALKING_API_KEY }}
      AFRICAS_TALKING_USERNAME: ${{ secrets.AFRICAS_TALKING_USERNAME }}
      AFRICAS_TALKING_SHORT_CODE: ${{ secrets.AFRICAS_TALKING_SHORT_CODE }}
      GO_ENV: ${{ secrets.GO_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2

      - name: Install dependencies
        run: go mod download

      - name: Build code
        run: go build -o divvly-tracking-service

      - name: Run server
        run: ./divvly-tracking-service & sleep 10

      - name: Run tests
        run: go test -v -timeout 300s ./tests

    
  deploy:
    runs-on: self-hosted
    if: true
    env:
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      AFRICAS_TALKING_API_KEY: ${{ secrets.AFRICAS_TALKING_API_KEY }}
      AFRICAS_TALKING_USERNAME: ${{ secrets.AFRICAS_TALKING_USERNAME }}
      AFRICAS_TALKING_SHORT_CODE: ${{ secrets.AFRICAS_TALKING_SHORT_CODE }}
      GO_ENV: ${{ secrets.GO_ENV }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up docker
        run: sudo bash ./scripts/docker_cleanup.sh

      - name: Build the docker image
        run: |
          docker build -t divvly-tracking-service \
          --build-arg MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING \
          --build-arg DB_USERNAME=$DB_USERNAME \
          --build-arg DB_PASSWORD=$secrets.DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_SSLMODE=$DB_SSLMODE \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg AFRICAS_TALKING_API_KEY=$AFRICAS_TALKING_API_KEY \
          --build-arg AFRICAS_TALKING_USERNAME=$AFRICAS_TALKING_USERNAME \
          --build-arg AFRICAS_TALKING_SHORT_CODE=$AFRICAS_TALKING_SHORT_CODE \
          --build-arg GO_ENV=$GO_ENV \
          .

      - name: Start the docker container
        run: docker run -d -p 8080:80 divvly-tracking-service

